config/routes.rb
Rssget::Application.routes.draw do
  resources :docs

  resources :euribors

  resources :stories

end

app/models/doc.rb
class Doc < ActiveRecord::Base
end

app/models/euribor.rb
class Euribor < ActiveRecord::Base
end

app/models/story.rb
class Story < ActiveRecord::Base
end

app/models/term.rb
class Term < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  # GET /docs
  # GET /docs.json
  def index
    @docs = Doc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @docs }
    end
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
    @doc = Doc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doc }
    end
  end

  # GET /docs/new
  # GET /docs/new.json
  def new
    @doc = Doc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doc }
    end
  end

  # GET /docs/1/edit
  def edit
    @doc = Doc.find(params[:id])
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = Doc.new(params[:doc])

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, notice: 'Doc was successfully created.' }
        format.json { render json: @doc, status: :created, location: @doc }
      else
        format.html { render action: "new" }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /docs/1
  # PUT /docs/1.json
  def update
    @doc = Doc.find(params[:id])

    respond_to do |format|
      if @doc.update_attributes(params[:doc])
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc = Doc.find(params[:id])
    @doc.destroy

    respond_to do |format|
      format.html { redirect_to docs_url }
      format.json { head :ok }
    end
  end
end

app/controllers/euribors_controller.rb
class EuriborsController < ApplicationController
  # GET /euribors
  # GET /euribors.json
  def index
    @euribors = Euribor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @euribors }
    end
  end

  # GET /euribors/1
  # GET /euribors/1.json
  def show
    @euribor = Euribor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @euribor }
    end
  end

  # GET /euribors/new
  # GET /euribors/new.json
  def new
    @euribor = Euribor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @euribor }
    end
  end

  # GET /euribors/1/edit
  def edit
    @euribor = Euribor.find(params[:id])
  end

  # POST /euribors
  # POST /euribors.json
  def create
    @euribor = Euribor.new(params[:euribor])

    respond_to do |format|
      if @euribor.save
        format.html { redirect_to @euribor, notice: 'Euribor was successfully created.' }
        format.json { render json: @euribor, status: :created, location: @euribor }
      else
        format.html { render action: "new" }
        format.json { render json: @euribor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /euribors/1
  # PUT /euribors/1.json
  def update
    @euribor = Euribor.find(params[:id])

    respond_to do |format|
      if @euribor.update_attributes(params[:euribor])
        format.html { redirect_to @euribor, notice: 'Euribor was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @euribor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /euribors/1
  # DELETE /euribors/1.json
  def destroy
    @euribor = Euribor.find(params[:id])
    @euribor.destroy

    respond_to do |format|
      format.html { redirect_to euribors_url }
      format.json { head :ok }
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
      format.xml {render xml: @stories}
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/euribors_helper.rb
module EuriborsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/docs/_form.html.erb
<%= form_for(@doc) do |f| %>
  <% if @doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% @doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :doc_id %><br />
    <%= f.number_field :doc_id %>
  </div>
  <div class="field">
    <%= f.label :real_doc_id %><br />
    <%= f.number_field :real_doc_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing doc</h1>

<%= render 'form' %>

<%= link_to 'Show', @doc %> |
<%= link_to 'Back', docs_path %>

app/views/docs/index.html.erb
<h1>Listing docs</h1>

<table>
  <tr>
    <th>Doc</th>
    <th>Real doc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @docs.each do |doc| %>
  <tr>
    <td><%= doc.doc_id %></td>
    <td><%= doc.real_doc_id %></td>
    <td><%= link_to 'Show', doc %></td>
    <td><%= link_to 'Edit', edit_doc_path(doc) %></td>
    <td><%= link_to 'Destroy', doc, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Doc', new_doc_path %>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= render 'form' %>

<%= link_to 'Back', docs_path %>

app/views/docs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Doc:</b>
  <%= @doc.doc_id %>
</p>

<p>
  <b>Real doc:</b>
  <%= @doc.real_doc_id %>
</p>


<%= link_to 'Edit', edit_doc_path(@doc) %> |
<%= link_to 'Back', docs_path %>

app/views/euribors/_form.html.erb
<%= form_for(@euribor) do |f| %>
  <% if @euribor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@euribor.errors.count, "error") %> prohibited this euribor from being saved:</h2>

      <ul>
      <% @euribor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :w1 %><br />
    <%= f.text_field :w1 %>
  </div>
  <div class="field">
    <%= f.label :w2 %><br />
    <%= f.text_field :w2 %>
  </div>
  <div class="field">
    <%= f.label :w3 %><br />
    <%= f.text_field :w3 %>
  </div>
  <div class="field">
    <%= f.label :m1 %><br />
    <%= f.text_field :m1 %>
  </div>
  <div class="field">
    <%= f.label :m2 %><br />
    <%= f.text_field :m2 %>
  </div>
  <div class="field">
    <%= f.label :m3 %><br />
    <%= f.text_field :m3 %>
  </div>
  <div class="field">
    <%= f.label :m4 %><br />
    <%= f.text_field :m4 %>
  </div>
  <div class="field">
    <%= f.label :m5 %><br />
    <%= f.text_field :m5 %>
  </div>
  <div class="field">
    <%= f.label :m6 %><br />
    <%= f.text_field :m6 %>
  </div>
  <div class="field">
    <%= f.label :m7 %><br />
    <%= f.text_field :m7 %>
  </div>
  <div class="field">
    <%= f.label :m8 %><br />
    <%= f.text_field :m8 %>
  </div>
  <div class="field">
    <%= f.label :m9 %><br />
    <%= f.text_field :m9 %>
  </div>
  <div class="field">
    <%= f.label :m10 %><br />
    <%= f.text_field :m10 %>
  </div>
  <div class="field">
    <%= f.label :m11 %><br />
    <%= f.text_field :m11 %>
  </div>
  <div class="field">
    <%= f.label :m12 %><br />
    <%= f.text_field :m12 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/euribors/edit.html.erb
<h1>Editing euribor</h1>

<%= render 'form' %>

<%= link_to 'Show', @euribor %> |
<%= link_to 'Back', euribors_path %>

app/views/euribors/index.html.erb
<h1>Listing euribors</h1>

<table>
  <tr>
    <th>Date</th>
    <th>W1</th>
    <th>W2</th>
    <th>W3</th>
    <th>M1</th>
    <th>M2</th>
    <th>M3</th>
    <th>M4</th>
    <th>M5</th>
    <th>M6</th>
    <th>M7</th>
    <th>M8</th>
    <th>M9</th>
    <th>M10</th>
    <th>M11</th>
    <th>M12</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @euribors.each do |euribor| %>
  <tr>
    <td><%= euribor.date %></td>
    <td><%= euribor.w1 %></td>
    <td><%= euribor.w2 %></td>
    <td><%= euribor.w3 %></td>
    <td><%= euribor.m1 %></td>
    <td><%= euribor.m2 %></td>
    <td><%= euribor.m3 %></td>
    <td><%= euribor.m4 %></td>
    <td><%= euribor.m5 %></td>
    <td><%= euribor.m6 %></td>
    <td><%= euribor.m7 %></td>
    <td><%= euribor.m8 %></td>
    <td><%= euribor.m9 %></td>
    <td><%= euribor.m10 %></td>
    <td><%= euribor.m11 %></td>
    <td><%= euribor.m12 %></td>
    <td><%= link_to 'Show', euribor %></td>
    <td><%= link_to 'Edit', edit_euribor_path(euribor) %></td>
    <td><%= link_to 'Destroy', euribor, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Euribor', new_euribor_path %>

app/views/euribors/new.html.erb
<h1>New euribor</h1>

<%= render 'form' %>

<%= link_to 'Back', euribors_path %>

app/views/euribors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @euribor.date %>
</p>

<p>
  <b>W1:</b>
  <%= @euribor.w1 %>
</p>

<p>
  <b>W2:</b>
  <%= @euribor.w2 %>
</p>

<p>
  <b>W3:</b>
  <%= @euribor.w3 %>
</p>

<p>
  <b>M1:</b>
  <%= @euribor.m1 %>
</p>

<p>
  <b>M2:</b>
  <%= @euribor.m2 %>
</p>

<p>
  <b>M3:</b>
  <%= @euribor.m3 %>
</p>

<p>
  <b>M4:</b>
  <%= @euribor.m4 %>
</p>

<p>
  <b>M5:</b>
  <%= @euribor.m5 %>
</p>

<p>
  <b>M6:</b>
  <%= @euribor.m6 %>
</p>

<p>
  <b>M7:</b>
  <%= @euribor.m7 %>
</p>

<p>
  <b>M8:</b>
  <%= @euribor.m8 %>
</p>

<p>
  <b>M9:</b>
  <%= @euribor.m9 %>
</p>

<p>
  <b>M10:</b>
  <%= @euribor.m10 %>
</p>

<p>
  <b>M11:</b>
  <%= @euribor.m11 %>
</p>

<p>
  <b>M12:</b>
  <%= @euribor.m12 %>
</p>


<%= link_to 'Edit', edit_euribor_path(@euribor) %> |
<%= link_to 'Back', euribors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rssget</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application_js" %> 
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <tr>
    <th>Topic</th>
    <th>Title</th>
    <th>Source</th>
    <th>Date</th>
    <th>Link</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stories.each do |story| %>
  <tr>
    <td><%= story.topic %></td>
    <td><%= story.title %></td>
    <td><%= story.source %></td>
    <td><%= story.date_time %></td>
    <td><%= story.link %></td>
    <td><%= story.content %></td>
    <td><%= link_to 'Show', story %></td>
    <td><%= link_to 'Edit', edit_story_path(story) %></td>
    <td><%= link_to 'Destroy', story, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @story.title %>
</p>

<p>
  <b>Title:</b>
  <%= @story.topic %>
</p>

<p>
  <b>Title:</b>
  <%= @story.source %>
</p>

<p>
  <b>Link:</b>
  <%= @story.link %>
</p>

<p>
  <b>Content:</b>
  <%= @story.content %>
</p>


<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>